apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ground-control.fullname" . }}
  labels:
    {{- include "ground-control.labels" . | nindent 4 }}
type: Opaque
stringData:
  HARBOR_URL: {{ .Values.harbor.url | quote }}
  HARBOR_USERNAME: {{ .Values.harbor.username | quote }}
  HARBOR_PASSWORD: {{ required "harbor.password is required" .Values.harbor.password | quote }}
  ADMIN_PASSWORD: {{ required "adminPassword is required" .Values.adminPassword | quote }}
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ required "database.password is required" .Values.database.password | quote }}
